#import env
spring.config.import=optional:file:.env.test[.properties]

#Configuracion de db test
spring.datasource.url=jdbc:mysql://localhost:3306/db_test_Trips
spring.datasource.username=root
spring.datasource.password=



jwt.secret="mysecretkeymysecretkeymysecretkey"