#import env
spring.config.import=optional:file:.env.dev[.properties]

#Configuracion de db dev
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

cookie.secure=false

super.email=${SUPER_EMAIL}
super.password=${SUPER_PASSWORD}


logging.level.org.springframework.security=DEBUG

