spring.application.name=trips

server.port=8080

#Perfiles
spring.profiles.active=dev

#Base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#logs 
logging.file.name=logs/trips.log







