name: Generate Javadoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Deploy Javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
